# Generated by Django 4.2 on 2023-05-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='update',
            field=models.DateField(blank=True),
        ),
    ]
