# Generated by Django 4.2 on 2023-05-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0002_alter_equipo_created_alter_equipo_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'manualServicio',
                'verbose_name_plural': 'manualServicios',
            },
        ),
    ]
