# Generated by Django 4.2 on 2023-05-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0003_manualservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('numero_parte', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
    ]
