# Generated by Django 4.2 on 2023-05-13 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0004_numparte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=30)),
                ('accesorio', models.CharField(blank=True, max_length=50, null=True)),
                ('contador', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(choices=[('Para alistar', 'Para alistar'), ('En alistamiento', 'En alistamiento'), ('Equipo listo', 'Equipo listo'), ('Equipo entregado', 'Equipo entregado'), ('Equipo para partes', 'Equipo para partes')], max_length=25)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('update', models.DateField(blank=True, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.modelo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.tecnico')),
            ],
            options={
                'verbose_name': 'alistamiento',
                'verbose_name_plural': 'alistamientos',
            },
        ),
    ]
