# Generated by Django 4.2 on 2023-05-13 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0005_alistamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoPartes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20, unique=True)),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('ubicacion', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(blank=True, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.modelo')),
            ],
        ),
    ]
