# Generated by Django 4.2 on 2023-05-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0006_equipopartes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'manualParte',
                'verbose_name_plural': 'manualPartes',
            },
        ),
    ]
