# Generated by Django 4.2 on 2023-05-26 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0007_manualparte'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumosTecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.tecnico')),
            ],
            options={
                'verbose_name': 'insumo',
                'verbose_name_plural': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='HerramientaTecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herramienta', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('prestamo', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.tecnico')),
            ],
            options={
                'verbose_name': 'herramienta',
                'verbose_name_plural': 'herramientas',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Multifuncional', 'Multifuncional'), ('Impresora', 'Impresora')], max_length=20)),
                ('bodega', models.CharField(max_length=20)),
                ('localizacion', models.CharField(max_length=20)),
                ('contador', models.CharField(max_length=7)),
                ('accesorio', models.TextField(max_length=100)),
                ('update', models.DateField()),
                ('diagnostico', models.TextField(max_length=100)),
                ('disponible', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.modelo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.tecnico')),
            ],
            options={
                'verbose_name': 'diagnostico',
                'verbose_name_plural': 'diagnosticos',
            },
        ),
    ]
