# Generated by Django 4.2 on 2023-05-06 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=30)),
                ('contacto', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(choices=[('RICOH', 'RICOH'), ('KYOCERA', 'KYOCERA'), ('KONICA-MINOLTA', 'KONICA-MINOLTA'), ('BROTHER', 'BROTHER'), ('HP', 'HP')], max_length=20)),
                ('modelo', models.CharField(max_length=10)),
                ('accesorio', models.TextField(max_length=100)),
                ('contador', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'manualParte',
                'verbose_name_plural': 'manualPartes',
            },
        ),
        migrations.CreateModel(
            name='ManualServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'manualServicio',
                'verbose_name_plural': 'manualServicios',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('modelo', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NumParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('numero_parte', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, null=True, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=15, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepuestoTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.modelo')),
                ('numero_parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.numparte')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipo1')),
            ],
        ),
        migrations.CreateModel(
            name='Alistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=30)),
                ('marca', models.CharField(choices=[('RICOH', 'RICOH'), ('KYOCERA', 'KYOCERA'), ('KONICA-MINOLTA', 'KONICA-MINOLTA'), ('BROTHER', 'BROTHER'), ('HP', 'HP')], max_length=20)),
                ('accesorio', models.CharField(max_length=50)),
                ('contador', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('Para alistar', 'Para alistar'), ('En alistamiento', 'En alistamiento'), ('Equipo listo', 'Equipo listo'), ('Equipo entregado', 'Equipo entregado'), ('Equipo para partes', 'Equipo para partes')], max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.modelo')),
            ],
            options={
                'verbose_name': 'alistamiento',
                'verbose_name_plural': 'alistamientos',
            },
        ),
    ]
